
sudo: required
services:
  - docker

script:
  - docker build -t /krisso-hub/nanny .
  - docker images krisso-hub/nanny
before_deploy:
  - docker login -u "krissohub" -p "Xpodigital12"
deploy: 
  provider: script
  script: docker push krisso-hub/nanny
  on:
    branch: master
